// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: ricart.proto

package mutexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DistributedMutexClient is the client API for DistributedMutex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributedMutexClient interface {
	// Request to access critical state
	RequestAccess(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Grants permission (reply) to a requesting node
	GrantPermission(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type distributedMutexClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedMutexClient(cc grpc.ClientConnInterface) DistributedMutexClient {
	return &distributedMutexClient{cc}
}

func (c *distributedMutexClient) RequestAccess(ctx context.Context, in *Request, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mutex.DistributedMutex/RequestAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedMutexClient) GrantPermission(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mutex.DistributedMutex/GrantPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedMutexServer is the server API for DistributedMutex service.
// All implementations must embed UnimplementedDistributedMutexServer
// for forward compatibility
type DistributedMutexServer interface {
	// Request to access critical state
	RequestAccess(context.Context, *Request) (*emptypb.Empty, error)
	// Grants permission (reply) to a requesting node
	GrantPermission(context.Context, *Reply) (*emptypb.Empty, error)
	mustEmbedUnimplementedDistributedMutexServer()
}

// UnimplementedDistributedMutexServer must be embedded to have forward compatible implementations.
type UnimplementedDistributedMutexServer struct {
}

func (UnimplementedDistributedMutexServer) RequestAccess(context.Context, *Request) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedDistributedMutexServer) GrantPermission(context.Context, *Reply) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantPermission not implemented")
}
func (UnimplementedDistributedMutexServer) mustEmbedUnimplementedDistributedMutexServer() {}

// UnsafeDistributedMutexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedMutexServer will
// result in compilation errors.
type UnsafeDistributedMutexServer interface {
	mustEmbedUnimplementedDistributedMutexServer()
}

func RegisterDistributedMutexServer(s grpc.ServiceRegistrar, srv DistributedMutexServer) {
	s.RegisterService(&DistributedMutex_ServiceDesc, srv)
}

func _DistributedMutex_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedMutexServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.DistributedMutex/RequestAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedMutexServer).RequestAccess(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedMutex_GrantPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedMutexServer).GrantPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.DistributedMutex/GrantPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedMutexServer).GrantPermission(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributedMutex_ServiceDesc is the grpc.ServiceDesc for DistributedMutex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedMutex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutex.DistributedMutex",
	HandlerType: (*DistributedMutexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAccess",
			Handler:    _DistributedMutex_RequestAccess_Handler,
		},
		{
			MethodName: "GrantPermission",
			Handler:    _DistributedMutex_GrantPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ricart.proto",
}
